Homework 3 is completed
Kamilla-Fazlyeva/KamillaFazlyeva pull request #6
Opened 2020-04-02 15:48 UTC by Kamilla-Fazlyeva

2020-04-03 20:01 UTC, DmitryKhodakovsky requested changes
Test does not work. 

Error:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 4, Time elapsed: 0.444 s <<< FAILURE! - in TestSuite
[ERROR] setUp(hw3.ex1.Exercise1)  Time elapsed: 0.353 s  <<< FAILURE!
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
        at hw3.ex1.Exercise1.setUp(Exercise1.java:14)

[ERROR] setUp(hw3.ex2.Exercise2)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
        at hw3.ex2.Exercise2.setUp(Exercise2.java:18)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   Exercise1.setUp:14->BaseClass.setUp:21 » IllegalState The path to the driver e...
[ERROR]   Exercise2.setUp:18->BaseClass.setUp:21 » IllegalState The path to the driver e...
[INFO] 
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.917 s
[INFO] Finished at: 2020-04-03T22:39:01+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project Kamilla_Fazlyeva_Homework: There are test failures.
```

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/composite/HeaderSection.java
> +    }
Why do you decide do not use inheritance for the `WebDriver` field and execution of the `PageFactory`?

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/composite/HeaderSection.java
> +    }
Could be used `stream` API for the collecting text

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/composite/LeftSection.java
> +    }
Why do you decide do not use inheritance for the `WebDriver` field and execution of the `PageFactory`?

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/voids/DifferentElementsPage.java
> +    private WebElement selenRadio;
I think it will be better define these elements as `Lists`. 
You will have 2 different lists of the elements.

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/voids/DifferentElementsPage.java
> +    private WebElement dropdownYellow;
I think this is enough for the element locator `//select[@class='uui-form-element'`.

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/voids/DifferentElementsPage.java
> +    }
Why do you do not use `Select` element?

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/voids/HomePage.java
> +    }
Why do you decide return `List<WebElement>`?

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/voids/HomePage.java
> +    }
Could be used `stream` API

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/main/java/hw3/composite/LeftSection.java
> +    }
Why do you decide return `List<WebElement>`?

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/test/java/hw3/base/BaseClass.java
> +        WebDriverManager.chromedriver().setup();
It will be better extract `WebDriverManager` to the `@BeforeSuite`

2020-04-03 20:01 UTC, DmitryKhodakovsky commented on src/test/java/hw3/ex1/Exercise1.java
> +        homePageAsserts = new HomePageAsserts(driver);
Why do you decide implement `Step` pattern?

2020-04-04 11:19 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/composite/HeaderSection.java
> +    }
I set the activation by default in one of the profiles. And only after that tests properly run with the command line

![Безымянный](https://user-images.githubusercontent.com/57841579/78434436-b7cf6280-767e-11ea-83db-438527230785.png)

2020-04-04 11:19 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/composite/HeaderSection.java
> +    }
Fixed

2020-04-04 11:20 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/composite/LeftSection.java
> +    }
The abstract page composite class is added

2020-04-04 11:20 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/voids/DifferentElementsPage.java
> +    private WebElement selenRadio;
Fixed

2020-04-04 11:20 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/voids/DifferentElementsPage.java
> +    private WebElement dropdownYellow;
Fixed

2020-04-04 11:20 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/voids/DifferentElementsPage.java
> +    }
Fixed

2020-04-04 11:20 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/voids/HomePage.java
> +    }
Fixed

2020-04-04 11:21 UTC, Kamilla-Fazlyeva commented on src/test/java/hw3/base/BaseClass.java
> +        WebDriverManager.chromedriver().setup();
Fixed

2020-04-04 11:26 UTC, Kamilla-Fazlyeva commented on src/test/java/hw3/ex1/Exercise1.java
> +        homePageAsserts = new HomePageAsserts(driver);
I thought it would be better to separate test actions from asserts. Is it not allowed for this homework?

2020-04-04 11:28 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/voids/HomePage.java
> +    }
Because in the method "shouldReturnImagesIndexPage" it needs to be checked that all of the images are displayed on the page

2020-04-04 11:31 UTC, Kamilla-Fazlyeva commented on src/main/java/hw3/composite/LeftSection.java
> +    }
Because in the method "shouldReturnLeftSectionItems" it needs to be checked that these items are displayed

2020-04-05 16:30 UTC, DmitryKhodakovsky approved these changes
Approved with minor comments

2020-04-05 16:30 UTC, DmitryKhodakovsky commented on src/main/java/hw3/composite/LeftSection.java
> +    }
it is be better to not return `WebElement` as is. However some practice allow us return webelements itself

2020-04-05 16:30 UTC, DmitryKhodakovsky commented on src/main/java/hw3/voids/DifferentElementsPage.java
> +    }
Looks like code duplication

2020-04-05 16:31 UTC, DmitryKhodakovsky commented on src/test/java/hw3/ex1/Exercise1.java
> +        homePageAsserts = new HomePageAsserts(driver);
Yeap, you are right. For this HW it does not required, but let stay its

2020-04-05 16:35 UTC, DmitryKhodakovsky commented
Could be merged to the master

2020-04-05 18:47 UTC, merged